// <auto-generated />
namespace IAE.Escola.Persistencia.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdicaoTelefone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicaoTelefone));
        
        string IMigrationMetadata.Id
        {
            get { return "201512041331412_AdicaoTelefone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
